#!/usr/bin/env python3
"""Collect every check the project runs into one report.

Three tools verify different things and each prints its own format, so nobody
reads all three. This runs them together and writes `docs/33-test-results.md`,
which the documentation site publishes like any other document.

The report records what ran, not what was hoped for: a tool that is absent is
reported absent rather than skipped silently.

    python3 report.py
"""

import re
import shutil
import subprocess
import sys
from datetime import datetime, timezone
from pathlib import Path

ROOT = Path(__file__).parent
OUT = ROOT / "docs" / "33-test-results.md"


def run(cmd, **kw):
    """Run a command, returning (ok, output). Never raises."""
    try:
        p = subprocess.run(cmd, capture_output=True, text=True, cwd=ROOT, timeout=600, **kw)
        return p.returncode == 0, p.stdout + p.stderr
    except FileNotFoundError:
        return None, f"{cmd[0]} is not installed"
    except subprocess.TimeoutExpired:
        return False, "timed out"


def strip_ansi(s):
    return re.sub(r"\033\[[0-9;]*m", "", s)


def main():
    stamp = datetime.now(timezone.utc).strftime("%d %B %Y, %H:%M UTC")
    rows, sections = [], []

    # ── documentation and model checks ──────────────────────────────────────

    ok, out = run([sys.executable, "verify.py", "--verbose"])
    out = strip_ansi(out)
    passed = len(re.findall(r"✓ L\d", out))
    failed = len(re.findall(r"✕ L\d", out))
    rows.append(("`verify.py`", "Documentation, models, code against specification",
                 f"{passed} passed, {failed} failed", ok))
    per_level = {}
    for lvl, _ in re.findall(r"✓ (L(\d))\.", out):
        per_level[lvl[:2]] = per_level.get(lvl[:2], 0) + 1
    sections.append(("Checks by level", "\n".join(
        f"| {lvl} | {n} |" for lvl, n in sorted(per_level.items())), ("Level", "Passing")))

    # ── the checks that verify the checks ───────────────────────────────────

    ok_self, out_self = run([sys.executable, "verify.py", "--self-test"])
    out_self = strip_ansi(out_self)
    m = re.search(r"(\d+)/(\d+) checks verified", out_self)
    rows.append(("`verify.py --self-test`", "Every check fails on its own broken fixture",
                 f"{m.group(1)} of {m.group(2)} alive" if m else "—", ok_self))

    # ── contracts ───────────────────────────────────────────────────────────

    if shutil.which("forge"):
        ok_b, _ = run(["forge", "build", "--sizes"])
        rows.append(("`forge build`", "Interfaces and storage layout compile",
                     "clean" if ok_b else "failed", ok_b))

        ok_t, out_t = run(["forge", "test", "-vv"])
        out_t = strip_ansi(out_t)
        m = re.search(r"(\d+) tests? passed, (\d+) failed", out_t)
        rows.append(("`forge test`", "Contract tests",
                     f"{m.group(1)} passed, {m.group(2)} failed" if m else "—", ok_t))
        tests = re.findall(r"\[(PASS|FAIL)\] (\w+)\(\) \(gas: (\d+)\)", out_t)
        if tests:
            sections.append(("Contract tests", "\n".join(
                f"| `{name}` | {'✅' if st == 'PASS' else '❌'} | {int(gas):,} |" for st, name, gas in tests),
                ("Test", "", "Gas")))

        ok_f, _ = run(["forge", "fmt", "--check"])
        rows.append(("`forge fmt --check`", "Formatting", "clean" if ok_f else "drift", ok_f))
    else:
        rows.append(("`forge`", "Contract build and tests", "not installed", None))

    # ── the open-boundary claim, as a grep ──────────────────────────────────

    known = "0x(096d75d0|b05cf4f6|25e60361|a832662d|85a3eae3|1cb9bd2c|998a0bea|e0c0f44a)"
    hit, _ = run(["grep", "-rniE", known, "src", "test"])
    clean = hit is False  # grep exits non-zero when it finds nothing
    rows.append(("Open boundary", "No Stobox address in contract source",
                 "clean" if clean else "**found**", clean))

    hit2, _ = run(["grep", "-rniE", r"\bSTBU\b", "src", "test"])
    rows.append(("Open boundary", "No STBU reference in contract source",
                 "clean" if hit2 is False else "**found**", hit2 is False))

    # ── write ───────────────────────────────────────────────────────────────

    def mark(ok):
        return "✅" if ok else ("⚠️" if ok is None else "❌")

    body = [
        "# 33 — Test results",
        "",
        "Generated by [`report.py`](../report.py); do not edit by hand.",
        "",
        f"**Run at {stamp}.**",
        "",
        "Everything the project verifies, in one place. Three tools check different things and each",
        "prints its own format, so on their own nobody reads all three.",
        "",
        "## Summary",
        "",
        "| | Tool | Checks | Result |",
        "|---|---|---|---|",
    ]
    for tool, what, result, ok in rows:
        body.append(f"| {mark(ok)} | {tool} | {what} | {result} |")

    for title, table, headers in sections:
        body += ["", f"## {title}", "", "| " + " | ".join(headers) + " |",
                 "|" + "---|" * len(headers), table]

    body += [
        "",
        "## What is not covered",
        "",
        "Stated because a green table invites the opposite reading.",
        "",
        "| Not covered | Arrives with |",
        "|---|---|",
        "| Runtime behaviour — the fifteen invariants in [17](17-security.md) | The implementation, Phase 1 |",
        "| Access modifiers against the documented roles — `L3.6` | The implementation |",
        "| Storage growth against a previous release — `L3.7` | The first tagged release |",
        "| Whether the specification is *right* | Review and the audit. No level can |",
        "",
        "## Related",
        "",
        "- [31 — Verification framework](31-verification.md) — what each level checks and cannot check",
        "- [23 — Testing plan](23-testing-plan.md) — what each phase must prove",
        "- [20 — Development plan](20-development-plan.md) — when the rest arrives",
        "",
    ]
    OUT.write_text("\n".join(body), encoding="utf-8")

    bad = sum(1 for *_, ok in rows if ok is False)
    print(f"  wrote {OUT.relative_to(ROOT)}")
    print(f"  {len(rows) - bad}/{len(rows)} green")
    return 1 if bad else 0


if __name__ == "__main__":
    sys.exit(main())
